<?php require 'templates/header.phtml' ?>
<form action="http://localhost/TPEWEB2/update1/" method="POST" class="form-control" >
    <label for="instrumento">instrumento:</label>
    <input type="text" name="instrumento" class="form-control" >
    <label for="precio">precio: </label>
    <input type="number" name="precio" class="form-control" >
    <label for="stock">stock:</label>
    <input type="number" name="stock" class="form-control" >
    <input type="hidden" name="id" value="<?php echo $id?>">
    <input type="submit" class="form-control">
</form>
<?php require 'templates/footer.phtml' ?>
