<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>MELOMANO</title>
</head>
<body>
    <!-- main header -->
    <header>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a href="instrumentos" class="navbar-brand">MELOMANO </a>
                <img src="img/musical-note-symbol-on-transparent-background-free-png.png" alt="" srcset="" class="img">
                <?php if(isset($this->user)): ?>
                    <span class="navbar-text"><?= $this->user->email?></span>
                <?php endif; ?> 
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <?php if(isset($this->user)): ?>
                            <li class="nav-item">
                                <a class="nav-link" id="salir" href="logout">Salir</a>
                            </li>
                        <?php endif;?>
                    </ul>
                </div>
            </div>
            </nav>
    </header>

    <main class="container mt-3">