<?php require 'templates/header.phtml'?>
<?php require 'templates/form.insertarmarcas.phtml'?>
<?php foreach($marcas as $key):?>
    <div class="list-group">
        <li class="list-group-item list-group-item-action" > 
        <?=$key->nombre_de_marca?> </li>
        <li class="list-group-item list-group-item-action"><?=$key->direccion?></li>
    </div>
        <?php if (!empty($key->ID_MARCAS)): ?>
            <a class="btn btn-danger" href=deletemarcas/<?=$key->ID_MARCAS?>>Borrar</a>
             <a class="btn btn-warning" href=updatemarcas/<?=$key->ID_MARCAS?>>actualizar</a>
            <a class="btn btn-info" href=itembymarca/<?=$key->ID_MARCAS?>>Mostrar instrumentos</a>
        <?php  endif?>
        <?php endforeach?>
        <?php require 'templates/footer.phtml'?>

