<?php require_once 'templates/header.phtml' ?>
<?php if($error):?>
<div class="alert alert-danger">
    <?=$error?>
</div>
<?php endif?>
<form method='post' action='login'>
    <div class='form-group'>
        <label for='email'>Email</label>
        <input type='email' class='form-control'  name='email' required>
    </div>
    <div class='form-group'>
        <label for='password'>Password</label>
        <input type='password' class='form-control'  name='contraseña' required>
    </div>
    <button type='submit' class='btn btn-primary'>Login</button>
</form>

<?php require 'templates/footer.phtml' ?>
