
<?php require 'templates/form.insertarinstrumentos.phtml'?>
<?php if (isset($error)): ?>
  <?=$error?>
    </div>
<?php endif; ?>
<?php if (!empty($instrumentosdb)): ?>
    <a class="btn btn-info" href="marcas">Mostrar Marcas</a>
    <?php foreach ($instrumentosdb as $index):?>
        <div class="list-group">
        <li  class="list-group-item list-group-item-action">Instrumento: <?= $index->instrumento ?></li>
        <?php foreach ($marcas as $key):?>
            <?php if ($key->ID_MARCAS===$index->ID_MARCAS): ?>
        <li  class="list-group-item list-group-item-action">Marca: <?= $key->nombre_de_marca?></li>
        <?php endif ?>
        <?php endforeach?>
        </div>
        <a  class="btn btn-info" href="mostrarmas/<?= $index->id ?>">Mostrar más</a>
        <a class="btn btn-danger" href="borrar/<?= $index->id ?>">Borrar</a>
        <a  class="btn btn-warning" href="update/<?= $index->id ?>">UPDATE</a>
    <?php endforeach?>
<?php endif ?>
<?php require 'templates/footer.phtml'?>

        
                    