<form action="http://localhost/TPEWEB2/updatemarcas1/" method="POST">
    <label for="nombre_de_marca">NOMBRE DE MARCA</label>
    <input type="text" name="nombre_de_marca" required>
    <label for="direccion">DIRECCION</label>
    <input type="text" name="direccion">
    <input type="hidden" name="ID_MARCAS" value="<?php  echo $id; ?>">
    <input type="submit" value="Actualizar">
</form>
