<div class="my-4">
<form action="insertar/" method="post" class="form-control">
    <label for="instrumentos">instrumento:</label>
    <input type="text" name="instrumento" class="form-control">
    <label for="precio">precio: </label>
    <input type="number" name="precio" class="form-control">
    <label for="stock">stock:</label>
    <input type="number" name="stock" class="form-control">
    <label for="ID_MARCAS">MARCAS</label>
    <select name="ID_MARCAS" id="" class="form-control">
        <?php if (!empty($instrumentosdb)&&!empty($marcas)):?>
            <?php foreach($marcas as $key):?>
            <option value="<?= $key->ID_MARCAS?>"><?=$key->nombre_de_marca?></option>
            <?php endforeach?>
            <?php endif ?>
    <input type="submit" class="btn btn-primary">
</form>
</div>