<form action="http://localhost/TPEWEB2/update1/" method="POST">
    <label for="instrumento">instrumento:</label>
    <input type="text" name="instrumento">
    <label for="precio">precio: </label>
    <input type="number" name="precio">
    <label for="stock">stock:</label>
    <input type="number" name="stock">
    <input type="hidden" name="id" value="<?php echo $id?>">
    <input type="submit">
</form>