<?php require 'layout/header.phtml'?>
<?php require 'templates/form.insertarmarcas.phtml'?>
<?php foreach($marcas as $key):?>
        <li> 
        <?=$key->nombre_de_marca?> </li>
        <li><?=$key->direccion?></li>
        <?php if (!empty($key->ID_MARCAS)): ?>
            <a href=deletemarcas/<?=$key->ID_MARCAS?>>Borrar</a>
             <a href=updatemarcas/<?=$key->ID_MARCAS?>>actualizar</a>
            <a href=itembymarca/<?=$key->ID_MARCAS?>>Mostrar instrumentos</a>
        <?php  endif?>
        <?php endforeach?>
        <?php require 'layout/footer.phtml'?>

